import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navigate from "./navigation/page"
import Login from "./login/page"
import Search from "./search/page"
import {CartProvider} from "./context/CartContext";

import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
    <div className="container">

         <CartProvider>
      <Navigate/> 
      <Login/>
      <Search/>
      
           {children}
          </CartProvider>
    
        </div></body>
    </html>
  );
}
